export const ICONS = [
  "format_list_bulleted",
  "bookmark",
  "push_pin",
  "push_pin",
  "push_pin",
  "card_giftcard",
  "cake",
  "school",
  "shopping_bag",
  "thermostat",
  "article",
  "menu_book",
  "wallet",
  "money",
  "kayaking",
  "directions_run",
  "food_bank",
  "wine_bar",
  "local_hospital",
  "sick",
  "chair",
  "home",
  "menu_book",
  "attach_money",
  "local_fire_department",
  "airplanemode_active",
  "alarm",
  "architecture",
  "account_balance",
  "add_alert",
  "add_reaction",
  "apartment",
  "attachment",
  "audiotrack",
  "baby_changing_station",
  "balance",
  "back_hand",
  "battery_charging_full",
  "bedtime",
  "blind",
  "bolt",
  "brightness_5",
  "calendar_month",
  "call",
  "campaign",
  "cancel",
  "candlestick_chart",
  "child_friendly",
  "church",
  "group",
  "square",
  "circle",
  "cloud",
  "favorite",
  "star"
];
export const COLORS = [
  "rgb(255, 69, 59)",
  "rgb(255, 158, 11)",
  "rgb(255, 213, 11)",
  "rgb(46, 209, 91)",
  "rgb(121, 195, 255)",
  "rgb(11, 132, 255)",
  "rgb(94, 92, 230)",
  "rgb(255, 79, 121)",
  "rgb(213, 127,245)",
  "rgb(201, 166, 118)",
  "rgb(114, 126, 135)",
  "rgb(234, 181, 174)"
];
